### ISSUE TITLE
did someone just break camera? I cannot install it again

### ISSUE THREAD

**Issue by culurciello** [clementfarabet/lua---camera#4]
[100%] Building CXX object macos/CMakeFiles/cammacos.dir/camera.m.o
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:120:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:75:24: error: expected identifier or '(' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:78:1: error: expected identifier before 'end'
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSResponder.h:9:0,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSView.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSText.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSActionCell.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:15,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:403:178: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:403:180: error: expected ')' before '(' token
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:17:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:34: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:36: error: expected ')' before '(' token
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:99: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:101: error: expected ')' before '(' token
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:54:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSDraggingItem.h:52:15: error: expected identifier or '(' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSDraggingItem.h:53:5: error: expected ';' before 'NSInteger'
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:73:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSSpellChecker.h:168:247: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSSpellChecker.h:168:249: error: expected ')' before '(' token
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:194:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSWindowRestoration.h:119:116: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSWindowRestoration.h:119:118: error: expected ')' before '(' token
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap snapshot]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:168:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:174:18: error: '-fobjc-exceptions' is required to enable Objective-C exception syntax
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap stopSession]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:201:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:205:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:207:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:209:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:212:7: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:215:7: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap startSession:withWidth:withHeight:]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:237:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:240:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:254:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:260:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:262:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:272:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:274:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:285:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:295:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:308:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:315:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:318:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:331:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:333:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function 'initCameras':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:423:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:427:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function 'grabFrames':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:446:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:448:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function 'luaopen_libcammacos':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:506:3: warning: implicit declaration of function 'luaL_openlib' [-Wimplicit-function-declaration]
make[2]: **\* [macos/CMakeFiles/cammacos.dir/camera.m.o] Error 1
make[1]: **\* [macos/CMakeFiles/cammacos.dir/all] Error 2
make: **\* [all] Error 2
[ 33%] Built documentation
[ 33%] Built target documentation-dok
[ 66%] Built target camopencv
[100%] Building CXX object macos/CMakeFiles/cammacos.dir/camera.m.o
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:120:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:75:24: error: expected identifier or '(' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:78:1: error: expected identifier before 'end'
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSResponder.h:9:0,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSView.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSText.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:10,
                 from /System/Library/Frameworks/AppKit.framework/Headers/NSActionCell.h:8,
                 from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:15,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:403:178: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:403:180: error: expected ')' before '(' token
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:17:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:34: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:36: error: expected ')' before '(' token
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:99: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:20:101: error: expected ')' before '(' token
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:54:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSDraggingItem.h:52:15: error: expected identifier or '(' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSDraggingItem.h:53:5: error: expected ';' before 'NSInteger'
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:73:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSSpellChecker.h:168:247: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSSpellChecker.h:168:249: error: expected ')' before '(' token
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:194:0,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.h:5,
                 from /Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:25:
/System/Library/Frameworks/AppKit.framework/Headers/NSWindowRestoration.h:119:116: error: expected ')' before '^' token
/System/Library/Frameworks/AppKit.framework/Headers/NSWindowRestoration.h:119:118: error: expected ')' before '(' token
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap snapshot]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:168:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:174:18: error: '-fobjc-exceptions' is required to enable Objective-C exception syntax
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap stopSession]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:201:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:205:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:207:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:209:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:212:7: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:215:7: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap startSession:withWidth:withHeight:]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:237:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:240:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:254:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:260:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:262:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:272:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:274:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:285:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:295:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:308:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:315:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:318:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function '-[ImageSnap captureOutput:didOutputVideoFrame:withSampleBuffer:fromConnection:]':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:331:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:333:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function 'initCameras':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:423:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:427:3: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function 'grabFrames':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:446:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:448:5: warning: value computed is not used [-Wunused-value]
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m: In function 'luaopen_libcammacos':
/Users/eugenioculurciello/.torch/torch-pkg/camera/macos/camera.m:506:3: warning: implicit declaration of function 'luaL_openlib' [-Wimplicit-function-declaration]
make[2]: **\* [macos/CMakeFiles/cammacos.dir/camera.m.o] Error 1
make[1]: **\* [macos/CMakeFiles/cammacos.dir/all] Error 2
make: **\* [all] Error 2

**Comment by culurciello** [comment]
fixed with:
PROBLEM: Oct 2012: camera package does not install with compiler: /usr/local/gfortran/bin/gcc

Solution: remove links to gfortran: 
export CC= 
export CXX= 

echo $CCX should return nothing
then you can install fine

**Comment by clementfarabet** [comment]
Ah crap, that was the problem?

Damn, this is weird.

Clément.

**Comment by culurciello** [comment]
thank to JT found out today!

**Comment by jtbates** [comment]
The problem is the Objective C in the macos wrapper.  I could get llvm-gcc to compile it by adding the flag -fobjc-exceptions but it still doesn't work with the gcc from gfortran.  I tried editing the cmake file in the macos directory to force clang but it was more involved than I expected.
